version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: main.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
      WERKZEUG_DEBUG_PIN: 'off'
    volumes:
      - ./app:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat
  redis:
    image: redis
    ports:
      - '6379:6379'
  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
      FLASK_DEBUG: 0

    volumes:
      - ./app:/app
    command: [celery, worker, --app=main.celery_app, --loglevel=INFO, --uid=nobody]
    depends_on:
      - redis
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
      FLASK_DEBUG: 1
    volumes:
      - ./app:/app
    command: [celery, beat, --app=main.celery_app, --loglevel=INFO]
    depends_on:
      - redis
  db:
    image: postgres:12
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: notif
      POSTGRES_USER: notif
      POSTGRES_PASSWORD: notif
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
